set_property(GLOBAL PROPERTY metal-ios-1.0 ${CMAKE_CURRENT_LIST_DIR}/metal-ios-1.0.conf)
set_property(GLOBAL PROPERTY metal-ios-1.1 ${CMAKE_CURRENT_LIST_DIR}/metal-ios-1.1.conf)
set_property(GLOBAL PROPERTY metal-ios-1.2 ${CMAKE_CURRENT_LIST_DIR}/metal-ios-1.2.conf)
set_property(GLOBAL PROPERTY metal-ios-2.0 ${CMAKE_CURRENT_LIST_DIR}/metal-ios-2.0.conf)
set_property(GLOBAL PROPERTY metal-ios-2.1 ${CMAKE_CURRENT_LIST_DIR}/metal-ios-2.1.conf)
set_property(GLOBAL PROPERTY metal-ios-2.2 ${CMAKE_CURRENT_LIST_DIR}/metal-ios-2.2.conf)
set_property(GLOBAL PROPERTY metal-ios-2.3 ${CMAKE_CURRENT_LIST_DIR}/metal-ios-2.3.conf)
set_property(GLOBAL PROPERTY metal-ios-2.4 ${CMAKE_CURRENT_LIST_DIR}/metal-ios-2.4.conf)

set_property(GLOBAL PROPERTY metal-macos-1.1 ${CMAKE_CURRENT_LIST_DIR}/metal-macos-1.1.conf)
set_property(GLOBAL PROPERTY metal-macos-1.2 ${CMAKE_CURRENT_LIST_DIR}/metal-macos-1.2.conf)
set_property(GLOBAL PROPERTY metal-macos-2.0 ${CMAKE_CURRENT_LIST_DIR}/metal-macos-2.0.conf)
set_property(GLOBAL PROPERTY metal-macos-2.1 ${CMAKE_CURRENT_LIST_DIR}/metal-macos-2.1.conf)
set_property(GLOBAL PROPERTY metal-macos-2.2 ${CMAKE_CURRENT_LIST_DIR}/metal-macos-2.2.conf)
set_property(GLOBAL PROPERTY metal-macos-2.3 ${CMAKE_CURRENT_LIST_DIR}/metal-macos-2.3.conf)
set_property(GLOBAL PROPERTY metal-macos-2.4 ${CMAKE_CURRENT_LIST_DIR}/metal-macos-2.4.conf)
