target = metal-ios
version = 1.0
define = subpassInput(i)=layout(input_attachment_index = i) subpassInput
define = DS_MIN_CLIP_Z=0.0
define = DS_CLIP_Z_TO_DEPTH_MUL=1.0
define = DS_CLIP_Z_TO_DEPTH_ADD=0.0
define = DS_DEPTH_TO_CLIP_Z_MUL=1.0
define = DS_DEPTH_TO_CLIP_Z_ADD=0.0
define = DS_ADJUST_CLIP(v)=(v)
define = DS_ADJUST_DIRECT_CLIP(v)=(v)
define = DS_RG_SWZL=rg
