# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaAnimation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DirectAnimation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DirectAnimation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDirectAnimation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DirectAnimation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DirectAnimation
    def Channels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from DeepSeaAnimation.DirectAnimationChannel import DirectAnimationChannel
            obj = DirectAnimationChannel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DirectAnimation
    def ChannelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DirectAnimation
    def ChannelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DirectAnimationStart(builder):
    builder.StartObject(1)

def Start(builder):
    DirectAnimationStart(builder)

def DirectAnimationAddChannels(builder, channels):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(channels), 0)

def AddChannels(builder, channels):
    DirectAnimationAddChannels(builder, channels)

def DirectAnimationStartChannelsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChannelsVector(builder, numElems):
    return DirectAnimationStartChannelsVector(builder, numElems)

def DirectAnimationEnd(builder):
    return builder.EndObject()

def End(builder):
    return DirectAnimationEnd(builder)
