# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaAnimation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KeyframeAnimation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KeyframeAnimation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKeyframeAnimation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KeyframeAnimation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KeyframeAnimation
    def Keyframes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from DeepSeaAnimation.AnimationKeyframes import AnimationKeyframes
            obj = AnimationKeyframes()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KeyframeAnimation
    def KeyframesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # KeyframeAnimation
    def KeyframesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def KeyframeAnimationStart(builder):
    builder.StartObject(1)

def Start(builder):
    KeyframeAnimationStart(builder)

def KeyframeAnimationAddKeyframes(builder, keyframes):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(keyframes), 0)

def AddKeyframes(builder, keyframes):
    KeyframeAnimationAddKeyframes(builder, keyframes)

def KeyframeAnimationStartKeyframesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartKeyframesVector(builder, numElems):
    return KeyframeAnimationStartKeyframesVector(builder, numElems)

def KeyframeAnimationEnd(builder):
    return builder.EndObject()

def End(builder):
    return KeyframeAnimationEnd(builder)
