# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaScenePhysics

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Constraint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Constraint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConstraint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Constraint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Constraint
    def Constraint(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Constraint
    def ConstraintAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Constraint
    def ConstraintLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Constraint
    def ConstraintIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Constraint
    def FirstRigidBodyInstance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Constraint
    def FirstConnectedConstraintInstance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Constraint
    def SecondRigidBodyInstance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Constraint
    def SecondConnectedConstraintInstance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ConstraintStart(builder):
    builder.StartObject(5)

def Start(builder):
    ConstraintStart(builder)

def ConstraintAddConstraint(builder, constraint):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(constraint), 0)

def AddConstraint(builder, constraint):
    ConstraintAddConstraint(builder, constraint)

def ConstraintStartConstraintVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartConstraintVector(builder, numElems):
    return ConstraintStartConstraintVector(builder, numElems)

def ConstraintAddFirstRigidBodyInstance(builder, firstRigidBodyInstance):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(firstRigidBodyInstance), 0)

def AddFirstRigidBodyInstance(builder, firstRigidBodyInstance):
    ConstraintAddFirstRigidBodyInstance(builder, firstRigidBodyInstance)

def ConstraintAddFirstConnectedConstraintInstance(builder, firstConnectedConstraintInstance):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(firstConnectedConstraintInstance), 0)

def AddFirstConnectedConstraintInstance(builder, firstConnectedConstraintInstance):
    ConstraintAddFirstConnectedConstraintInstance(builder, firstConnectedConstraintInstance)

def ConstraintAddSecondRigidBodyInstance(builder, secondRigidBodyInstance):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(secondRigidBodyInstance), 0)

def AddSecondRigidBodyInstance(builder, secondRigidBodyInstance):
    ConstraintAddSecondRigidBodyInstance(builder, secondRigidBodyInstance)

def ConstraintAddSecondConnectedConstraintInstance(builder, secondConnectedConstraintInstance):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(secondConnectedConstraintInstance), 0)

def AddSecondConnectedConstraintInstance(builder, secondConnectedConstraintInstance):
    ConstraintAddSecondConnectedConstraintInstance(builder, secondConnectedConstraintInstance)

def ConstraintEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConstraintEnd(builder)
