# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaVectorDrawScene

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MeterialElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMeterialElement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MeterialElement()
        x.Init(buf, n + offset)
        return x

    # MeterialElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MeterialElement
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MeterialElement
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MeterialElement
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MeterialElement
    def Binding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MeterialElement
    def ShaderVariableGroupDesc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MeterialElementStart(builder): builder.StartObject(5)
def MeterialElementAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def MeterialElementAddType(builder, type): builder.PrependUint8Slot(1, type, 0)
def MeterialElementAddCount(builder, count): builder.PrependUint32Slot(2, count, 0)
def MeterialElementAddBinding(builder, binding): builder.PrependUint8Slot(3, binding, 0)
def MeterialElementAddShaderVariableGroupDesc(builder, shaderVariableGroupDesc): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(shaderVariableGroupDesc), 0)
def MeterialElementEnd(builder): return builder.EndObject()
