# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaVectorDrawScene

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SceneText(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SceneText()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSceneText(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SceneText
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SceneText
    def Font(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from DeepSeaVectorDrawScene.VectorResourceRef import VectorResourceRef
            obj = VectorResourceRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SceneText
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SceneText
    def Styles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from DeepSeaVectorDrawScene.SceneTextStyle import SceneTextStyle
            obj = SceneTextStyle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SceneText
    def StylesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SceneText
    def StylesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def SceneTextStart(builder): builder.StartObject(3)
def Start(builder):
    return SceneTextStart(builder)
def SceneTextAddFont(builder, font): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(font), 0)
def AddFont(builder, font):
    return SceneTextAddFont(builder, font)
def SceneTextAddText(builder, text): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)
def AddText(builder, text):
    return SceneTextAddText(builder, text)
def SceneTextAddStyles(builder, styles): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(styles), 0)
def AddStyles(builder, styles):
    return SceneTextAddStyles(builder, styles)
def SceneTextStartStylesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartStylesVector(builder, numElems):
    return SceneTextStartStylesVector(builder, numElems)
def SceneTextEnd(builder): return builder.EndObject()
def End(builder):
    return SceneTextEnd(builder)