// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_REVOLUTEPHYSICSCONSTRAINT_DEEPSEAPHYSICS_H_
#define FLATBUFFERS_GENERATED_REVOLUTEPHYSICSCONSTRAINT_DEEPSEAPHYSICS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "PhysicsCommon_generated.h"

namespace DeepSeaPhysics {

struct RevoluteConstraint;
struct RevoluteConstraintBuilder;

struct RevoluteConstraint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RevoluteConstraintBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FIRSTACTOR = 4,
    VT_FIRSTPOSITION = 6,
    VT_FIRSTROTATION = 8,
    VT_SECONDACTOR = 10,
    VT_SECONDPOSITION = 12,
    VT_SECONDROTATION = 14,
    VT_LIMITENABLED = 16,
    VT_MINANGLE = 18,
    VT_MAXANGLE = 20,
    VT_LIMITSTIFFNESS = 22,
    VT_LIMITDAMPING = 24,
    VT_MOTORTYPE = 26,
    VT_MOTORTARGET = 28,
    VT_MAXMOTORTORQUE = 30
  };
  const ::flatbuffers::String *firstActor() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FIRSTACTOR);
  }
  const DeepSeaPhysics::Vector3f *firstPosition() const {
    return GetStruct<const DeepSeaPhysics::Vector3f *>(VT_FIRSTPOSITION);
  }
  const DeepSeaPhysics::Quaternion4f *firstRotation() const {
    return GetStruct<const DeepSeaPhysics::Quaternion4f *>(VT_FIRSTROTATION);
  }
  const ::flatbuffers::String *secondActor() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SECONDACTOR);
  }
  const DeepSeaPhysics::Vector3f *secondPosition() const {
    return GetStruct<const DeepSeaPhysics::Vector3f *>(VT_SECONDPOSITION);
  }
  const DeepSeaPhysics::Quaternion4f *secondRotation() const {
    return GetStruct<const DeepSeaPhysics::Quaternion4f *>(VT_SECONDROTATION);
  }
  bool limitEnabled() const {
    return GetField<uint8_t>(VT_LIMITENABLED, 0) != 0;
  }
  float minAngle() const {
    return GetField<float>(VT_MINANGLE, 0.0f);
  }
  float maxAngle() const {
    return GetField<float>(VT_MAXANGLE, 0.0f);
  }
  float limitStiffness() const {
    return GetField<float>(VT_LIMITSTIFFNESS, 0.0f);
  }
  float limitDamping() const {
    return GetField<float>(VT_LIMITDAMPING, 0.0f);
  }
  DeepSeaPhysics::ConstraintMotorType motorType() const {
    return static_cast<DeepSeaPhysics::ConstraintMotorType>(GetField<uint8_t>(VT_MOTORTYPE, 0));
  }
  float motorTarget() const {
    return GetField<float>(VT_MOTORTARGET, 0.0f);
  }
  float maxMotorTorque() const {
    return GetField<float>(VT_MAXMOTORTORQUE, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_FIRSTACTOR) &&
           verifier.VerifyString(firstActor()) &&
           VerifyFieldRequired<DeepSeaPhysics::Vector3f>(verifier, VT_FIRSTPOSITION, 4) &&
           VerifyFieldRequired<DeepSeaPhysics::Quaternion4f>(verifier, VT_FIRSTROTATION, 4) &&
           VerifyOffsetRequired(verifier, VT_SECONDACTOR) &&
           verifier.VerifyString(secondActor()) &&
           VerifyFieldRequired<DeepSeaPhysics::Vector3f>(verifier, VT_SECONDPOSITION, 4) &&
           VerifyFieldRequired<DeepSeaPhysics::Quaternion4f>(verifier, VT_SECONDROTATION, 4) &&
           VerifyField<uint8_t>(verifier, VT_LIMITENABLED, 1) &&
           VerifyField<float>(verifier, VT_MINANGLE, 4) &&
           VerifyField<float>(verifier, VT_MAXANGLE, 4) &&
           VerifyField<float>(verifier, VT_LIMITSTIFFNESS, 4) &&
           VerifyField<float>(verifier, VT_LIMITDAMPING, 4) &&
           VerifyField<uint8_t>(verifier, VT_MOTORTYPE, 1) &&
           VerifyField<float>(verifier, VT_MOTORTARGET, 4) &&
           VerifyField<float>(verifier, VT_MAXMOTORTORQUE, 4) &&
           verifier.EndTable();
  }
};

struct RevoluteConstraintBuilder {
  typedef RevoluteConstraint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_firstActor(::flatbuffers::Offset<::flatbuffers::String> firstActor) {
    fbb_.AddOffset(RevoluteConstraint::VT_FIRSTACTOR, firstActor);
  }
  void add_firstPosition(const DeepSeaPhysics::Vector3f *firstPosition) {
    fbb_.AddStruct(RevoluteConstraint::VT_FIRSTPOSITION, firstPosition);
  }
  void add_firstRotation(const DeepSeaPhysics::Quaternion4f *firstRotation) {
    fbb_.AddStruct(RevoluteConstraint::VT_FIRSTROTATION, firstRotation);
  }
  void add_secondActor(::flatbuffers::Offset<::flatbuffers::String> secondActor) {
    fbb_.AddOffset(RevoluteConstraint::VT_SECONDACTOR, secondActor);
  }
  void add_secondPosition(const DeepSeaPhysics::Vector3f *secondPosition) {
    fbb_.AddStruct(RevoluteConstraint::VT_SECONDPOSITION, secondPosition);
  }
  void add_secondRotation(const DeepSeaPhysics::Quaternion4f *secondRotation) {
    fbb_.AddStruct(RevoluteConstraint::VT_SECONDROTATION, secondRotation);
  }
  void add_limitEnabled(bool limitEnabled) {
    fbb_.AddElement<uint8_t>(RevoluteConstraint::VT_LIMITENABLED, static_cast<uint8_t>(limitEnabled), 0);
  }
  void add_minAngle(float minAngle) {
    fbb_.AddElement<float>(RevoluteConstraint::VT_MINANGLE, minAngle, 0.0f);
  }
  void add_maxAngle(float maxAngle) {
    fbb_.AddElement<float>(RevoluteConstraint::VT_MAXANGLE, maxAngle, 0.0f);
  }
  void add_limitStiffness(float limitStiffness) {
    fbb_.AddElement<float>(RevoluteConstraint::VT_LIMITSTIFFNESS, limitStiffness, 0.0f);
  }
  void add_limitDamping(float limitDamping) {
    fbb_.AddElement<float>(RevoluteConstraint::VT_LIMITDAMPING, limitDamping, 0.0f);
  }
  void add_motorType(DeepSeaPhysics::ConstraintMotorType motorType) {
    fbb_.AddElement<uint8_t>(RevoluteConstraint::VT_MOTORTYPE, static_cast<uint8_t>(motorType), 0);
  }
  void add_motorTarget(float motorTarget) {
    fbb_.AddElement<float>(RevoluteConstraint::VT_MOTORTARGET, motorTarget, 0.0f);
  }
  void add_maxMotorTorque(float maxMotorTorque) {
    fbb_.AddElement<float>(RevoluteConstraint::VT_MAXMOTORTORQUE, maxMotorTorque, 0.0f);
  }
  explicit RevoluteConstraintBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RevoluteConstraint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RevoluteConstraint>(end);
    fbb_.Required(o, RevoluteConstraint::VT_FIRSTACTOR);
    fbb_.Required(o, RevoluteConstraint::VT_FIRSTPOSITION);
    fbb_.Required(o, RevoluteConstraint::VT_FIRSTROTATION);
    fbb_.Required(o, RevoluteConstraint::VT_SECONDACTOR);
    fbb_.Required(o, RevoluteConstraint::VT_SECONDPOSITION);
    fbb_.Required(o, RevoluteConstraint::VT_SECONDROTATION);
    return o;
  }
};

inline ::flatbuffers::Offset<RevoluteConstraint> CreateRevoluteConstraint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> firstActor = 0,
    const DeepSeaPhysics::Vector3f *firstPosition = nullptr,
    const DeepSeaPhysics::Quaternion4f *firstRotation = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> secondActor = 0,
    const DeepSeaPhysics::Vector3f *secondPosition = nullptr,
    const DeepSeaPhysics::Quaternion4f *secondRotation = nullptr,
    bool limitEnabled = false,
    float minAngle = 0.0f,
    float maxAngle = 0.0f,
    float limitStiffness = 0.0f,
    float limitDamping = 0.0f,
    DeepSeaPhysics::ConstraintMotorType motorType = DeepSeaPhysics::ConstraintMotorType::Disabled,
    float motorTarget = 0.0f,
    float maxMotorTorque = 0.0f) {
  RevoluteConstraintBuilder builder_(_fbb);
  builder_.add_maxMotorTorque(maxMotorTorque);
  builder_.add_motorTarget(motorTarget);
  builder_.add_limitDamping(limitDamping);
  builder_.add_limitStiffness(limitStiffness);
  builder_.add_maxAngle(maxAngle);
  builder_.add_minAngle(minAngle);
  builder_.add_secondRotation(secondRotation);
  builder_.add_secondPosition(secondPosition);
  builder_.add_secondActor(secondActor);
  builder_.add_firstRotation(firstRotation);
  builder_.add_firstPosition(firstPosition);
  builder_.add_firstActor(firstActor);
  builder_.add_motorType(motorType);
  builder_.add_limitEnabled(limitEnabled);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RevoluteConstraint> CreateRevoluteConstraintDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *firstActor = nullptr,
    const DeepSeaPhysics::Vector3f *firstPosition = nullptr,
    const DeepSeaPhysics::Quaternion4f *firstRotation = nullptr,
    const char *secondActor = nullptr,
    const DeepSeaPhysics::Vector3f *secondPosition = nullptr,
    const DeepSeaPhysics::Quaternion4f *secondRotation = nullptr,
    bool limitEnabled = false,
    float minAngle = 0.0f,
    float maxAngle = 0.0f,
    float limitStiffness = 0.0f,
    float limitDamping = 0.0f,
    DeepSeaPhysics::ConstraintMotorType motorType = DeepSeaPhysics::ConstraintMotorType::Disabled,
    float motorTarget = 0.0f,
    float maxMotorTorque = 0.0f) {
  auto firstActor__ = firstActor ? _fbb.CreateString(firstActor) : 0;
  auto secondActor__ = secondActor ? _fbb.CreateString(secondActor) : 0;
  return DeepSeaPhysics::CreateRevoluteConstraint(
      _fbb,
      firstActor__,
      firstPosition,
      firstRotation,
      secondActor__,
      secondPosition,
      secondRotation,
      limitEnabled,
      minAngle,
      maxAngle,
      limitStiffness,
      limitDamping,
      motorType,
      motorTarget,
      maxMotorTorque);
}

inline const DeepSeaPhysics::RevoluteConstraint *GetRevoluteConstraint(const void *buf) {
  return ::flatbuffers::GetRoot<DeepSeaPhysics::RevoluteConstraint>(buf);
}

inline const DeepSeaPhysics::RevoluteConstraint *GetSizePrefixedRevoluteConstraint(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<DeepSeaPhysics::RevoluteConstraint>(buf);
}

inline bool VerifyRevoluteConstraintBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<DeepSeaPhysics::RevoluteConstraint>(nullptr);
}

inline bool VerifySizePrefixedRevoluteConstraintBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<DeepSeaPhysics::RevoluteConstraint>(nullptr);
}

inline void FinishRevoluteConstraintBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DeepSeaPhysics::RevoluteConstraint> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRevoluteConstraintBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DeepSeaPhysics::RevoluteConstraint> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DeepSeaPhysics

#endif  // FLATBUFFERS_GENERATED_REVOLUTEPHYSICSCONSTRAINT_DEEPSEAPHYSICS_H_
