// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ANIMATIONTREE_DEEPSEAANIMATION_H_
#define FLATBUFFERS_GENERATED_ANIMATIONTREE_DEEPSEAANIMATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

#include "AnimationCommon_generated.h"

namespace DeepSeaAnimation {

struct AnimationTreeNode;
struct AnimationTreeNodeBuilder;

struct AnimationJointTreeNode;
struct AnimationJointTreeNodeBuilder;

struct AnimationTree;
struct AnimationTreeBuilder;

struct AnimationTreeNode FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimationTreeNodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SCALE = 6,
    VT_ROTATION = 8,
    VT_TRANSLATION = 10,
    VT_CHILDREN = 12
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const DeepSeaAnimation::Vector3f *scale() const {
    return GetStruct<const DeepSeaAnimation::Vector3f *>(VT_SCALE);
  }
  const DeepSeaAnimation::Quaternion4f *rotation() const {
    return GetStruct<const DeepSeaAnimation::Quaternion4f *>(VT_ROTATION);
  }
  const DeepSeaAnimation::Vector3f *translation() const {
    return GetStruct<const DeepSeaAnimation::Vector3f *>(VT_TRANSLATION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>> *children() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>> *>(VT_CHILDREN);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<DeepSeaAnimation::Vector3f>(verifier, VT_SCALE, 4) &&
           VerifyField<DeepSeaAnimation::Quaternion4f>(verifier, VT_ROTATION, 4) &&
           VerifyField<DeepSeaAnimation::Vector3f>(verifier, VT_TRANSLATION, 4) &&
           VerifyOffset(verifier, VT_CHILDREN) &&
           verifier.VerifyVector(children()) &&
           verifier.VerifyVectorOfTables(children()) &&
           verifier.EndTable();
  }
};

struct AnimationTreeNodeBuilder {
  typedef AnimationTreeNode Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(AnimationTreeNode::VT_NAME, name);
  }
  void add_scale(const DeepSeaAnimation::Vector3f *scale) {
    fbb_.AddStruct(AnimationTreeNode::VT_SCALE, scale);
  }
  void add_rotation(const DeepSeaAnimation::Quaternion4f *rotation) {
    fbb_.AddStruct(AnimationTreeNode::VT_ROTATION, rotation);
  }
  void add_translation(const DeepSeaAnimation::Vector3f *translation) {
    fbb_.AddStruct(AnimationTreeNode::VT_TRANSLATION, translation);
  }
  void add_children(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>>> children) {
    fbb_.AddOffset(AnimationTreeNode::VT_CHILDREN, children);
  }
  explicit AnimationTreeNodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnimationTreeNode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnimationTreeNode>(end);
    fbb_.Required(o, AnimationTreeNode::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<AnimationTreeNode> CreateAnimationTreeNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const DeepSeaAnimation::Vector3f *scale = nullptr,
    const DeepSeaAnimation::Quaternion4f *rotation = nullptr,
    const DeepSeaAnimation::Vector3f *translation = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>>> children = 0) {
  AnimationTreeNodeBuilder builder_(_fbb);
  builder_.add_children(children);
  builder_.add_translation(translation);
  builder_.add_rotation(rotation);
  builder_.add_scale(scale);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AnimationTreeNode> CreateAnimationTreeNodeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const DeepSeaAnimation::Vector3f *scale = nullptr,
    const DeepSeaAnimation::Quaternion4f *rotation = nullptr,
    const DeepSeaAnimation::Vector3f *translation = nullptr,
    const std::vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>> *children = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto children__ = children ? _fbb.CreateVector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>>(*children) : 0;
  return DeepSeaAnimation::CreateAnimationTreeNode(
      _fbb,
      name__,
      scale,
      rotation,
      translation,
      children__);
}

struct AnimationJointTreeNode FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimationJointTreeNodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SCALE = 6,
    VT_ROTATION = 8,
    VT_TRANSLATION = 10,
    VT_TOLOCALSPACE = 12,
    VT_CHILDREN = 14
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const DeepSeaAnimation::Vector3f *scale() const {
    return GetStruct<const DeepSeaAnimation::Vector3f *>(VT_SCALE);
  }
  const DeepSeaAnimation::Quaternion4f *rotation() const {
    return GetStruct<const DeepSeaAnimation::Quaternion4f *>(VT_ROTATION);
  }
  const DeepSeaAnimation::Vector3f *translation() const {
    return GetStruct<const DeepSeaAnimation::Vector3f *>(VT_TRANSLATION);
  }
  const DeepSeaAnimation::Matrix44f *toLocalSpace() const {
    return GetStruct<const DeepSeaAnimation::Matrix44f *>(VT_TOLOCALSPACE);
  }
  const ::flatbuffers::Vector<uint32_t> *children() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_CHILDREN);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<DeepSeaAnimation::Vector3f>(verifier, VT_SCALE, 4) &&
           VerifyField<DeepSeaAnimation::Quaternion4f>(verifier, VT_ROTATION, 4) &&
           VerifyField<DeepSeaAnimation::Vector3f>(verifier, VT_TRANSLATION, 4) &&
           VerifyFieldRequired<DeepSeaAnimation::Matrix44f>(verifier, VT_TOLOCALSPACE, 4) &&
           VerifyOffset(verifier, VT_CHILDREN) &&
           verifier.VerifyVector(children()) &&
           verifier.EndTable();
  }
};

struct AnimationJointTreeNodeBuilder {
  typedef AnimationJointTreeNode Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(AnimationJointTreeNode::VT_NAME, name);
  }
  void add_scale(const DeepSeaAnimation::Vector3f *scale) {
    fbb_.AddStruct(AnimationJointTreeNode::VT_SCALE, scale);
  }
  void add_rotation(const DeepSeaAnimation::Quaternion4f *rotation) {
    fbb_.AddStruct(AnimationJointTreeNode::VT_ROTATION, rotation);
  }
  void add_translation(const DeepSeaAnimation::Vector3f *translation) {
    fbb_.AddStruct(AnimationJointTreeNode::VT_TRANSLATION, translation);
  }
  void add_toLocalSpace(const DeepSeaAnimation::Matrix44f *toLocalSpace) {
    fbb_.AddStruct(AnimationJointTreeNode::VT_TOLOCALSPACE, toLocalSpace);
  }
  void add_children(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> children) {
    fbb_.AddOffset(AnimationJointTreeNode::VT_CHILDREN, children);
  }
  explicit AnimationJointTreeNodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnimationJointTreeNode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnimationJointTreeNode>(end);
    fbb_.Required(o, AnimationJointTreeNode::VT_NAME);
    fbb_.Required(o, AnimationJointTreeNode::VT_TOLOCALSPACE);
    return o;
  }
};

inline ::flatbuffers::Offset<AnimationJointTreeNode> CreateAnimationJointTreeNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const DeepSeaAnimation::Vector3f *scale = nullptr,
    const DeepSeaAnimation::Quaternion4f *rotation = nullptr,
    const DeepSeaAnimation::Vector3f *translation = nullptr,
    const DeepSeaAnimation::Matrix44f *toLocalSpace = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> children = 0) {
  AnimationJointTreeNodeBuilder builder_(_fbb);
  builder_.add_children(children);
  builder_.add_toLocalSpace(toLocalSpace);
  builder_.add_translation(translation);
  builder_.add_rotation(rotation);
  builder_.add_scale(scale);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AnimationJointTreeNode> CreateAnimationJointTreeNodeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const DeepSeaAnimation::Vector3f *scale = nullptr,
    const DeepSeaAnimation::Quaternion4f *rotation = nullptr,
    const DeepSeaAnimation::Vector3f *translation = nullptr,
    const DeepSeaAnimation::Matrix44f *toLocalSpace = nullptr,
    const std::vector<uint32_t> *children = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto children__ = children ? _fbb.CreateVector<uint32_t>(*children) : 0;
  return DeepSeaAnimation::CreateAnimationJointTreeNode(
      _fbb,
      name__,
      scale,
      rotation,
      translation,
      toLocalSpace,
      children__);
}

struct AnimationTree FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimationTreeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOTNODES = 4,
    VT_JOINTNODES = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>> *rootNodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>> *>(VT_ROOTNODES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationJointTreeNode>> *jointNodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationJointTreeNode>> *>(VT_JOINTNODES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ROOTNODES) &&
           verifier.VerifyVector(rootNodes()) &&
           verifier.VerifyVectorOfTables(rootNodes()) &&
           VerifyOffset(verifier, VT_JOINTNODES) &&
           verifier.VerifyVector(jointNodes()) &&
           verifier.VerifyVectorOfTables(jointNodes()) &&
           verifier.EndTable();
  }
};

struct AnimationTreeBuilder {
  typedef AnimationTree Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rootNodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>>> rootNodes) {
    fbb_.AddOffset(AnimationTree::VT_ROOTNODES, rootNodes);
  }
  void add_jointNodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationJointTreeNode>>> jointNodes) {
    fbb_.AddOffset(AnimationTree::VT_JOINTNODES, jointNodes);
  }
  explicit AnimationTreeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnimationTree> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnimationTree>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnimationTree> CreateAnimationTree(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>>> rootNodes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationJointTreeNode>>> jointNodes = 0) {
  AnimationTreeBuilder builder_(_fbb);
  builder_.add_jointNodes(jointNodes);
  builder_.add_rootNodes(rootNodes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AnimationTree> CreateAnimationTreeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>> *rootNodes = nullptr,
    const std::vector<::flatbuffers::Offset<DeepSeaAnimation::AnimationJointTreeNode>> *jointNodes = nullptr) {
  auto rootNodes__ = rootNodes ? _fbb.CreateVector<::flatbuffers::Offset<DeepSeaAnimation::AnimationTreeNode>>(*rootNodes) : 0;
  auto jointNodes__ = jointNodes ? _fbb.CreateVector<::flatbuffers::Offset<DeepSeaAnimation::AnimationJointTreeNode>>(*jointNodes) : 0;
  return DeepSeaAnimation::CreateAnimationTree(
      _fbb,
      rootNodes__,
      jointNodes__);
}

inline const DeepSeaAnimation::AnimationTree *GetAnimationTree(const void *buf) {
  return ::flatbuffers::GetRoot<DeepSeaAnimation::AnimationTree>(buf);
}

inline const DeepSeaAnimation::AnimationTree *GetSizePrefixedAnimationTree(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<DeepSeaAnimation::AnimationTree>(buf);
}

inline bool VerifyAnimationTreeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<DeepSeaAnimation::AnimationTree>(nullptr);
}

inline bool VerifySizePrefixedAnimationTreeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<DeepSeaAnimation::AnimationTree>(nullptr);
}

inline void FinishAnimationTreeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DeepSeaAnimation::AnimationTree> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAnimationTreeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DeepSeaAnimation::AnimationTree> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DeepSeaAnimation

#endif  // FLATBUFFERS_GENERATED_ANIMATIONTREE_DEEPSEAANIMATION_H_
