target = glsl
version = 440
define = subpassInput(i)=sampler2D
define = subpassLoad(sampler)=texture(sampler, gl_FragCoord.xy*uniforms._dsInternal0.zw)
define = DS_MIN_CLIP_Z=uniforms._dsInternal1.w
define = DS_CLIP_Z_TO_DEPTH_MUL=uniforms._dsInternal1.x
define = DS_CLIP_Z_TO_DEPTH_ADD=uniforms._dsInternal1.y
define = DS_DEPTH_TO_CLIP_Z_MUL=uniforms._dsInternal1.z
define = DS_DEPTH_TO_CLIP_Z_ADD=uniforms._dsInternal1.w
define = DS_ADJUST_CLIP(v)=((v)*vec4(1.0, uniforms._dsInternal0.x, 1.0, 1.0))
define = DS_ADJUST_DIRECT_CLIP(v)=((v)*vec4(1.0, uniforms._dsInternal0.x, 1.0, 1.0))
define = DS_RG_SWZL=rg
# frag/clip y multiplier, frag y addition, subpass frag coord x/y multiplier
pre-header-line = uniform vec4 _dsInternal0;
# clip z to depth multiplier, clip z to depth addition, depth to clip z multiplier, depth to clip z addition
pre-header-line = uniform vec4 _dsInternal1;
# Use header line to ensure define is applied after code generation is run.
header-line-frag = @define gl_FragCoord vec4(gl_FragCoord.x, gl_FragCoord.y*uniforms._dsInternal0.x + uniforms._dsInternal0.y, gl_FragCoord.zw)
