# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaScene

import flatbuffers

class AttachmentInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAttachmentInfo(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AttachmentInfo()
        x.Init(buf, n + offset)
        return x

    # AttachmentInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AttachmentInfo
    def Usage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AttachmentInfo
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # AttachmentInfo
    def Samples(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AttachmentInfo
    def ClearValueType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # AttachmentInfo
    def ClearValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def AttachmentInfoStart(builder): builder.StartObject(5)
def AttachmentInfoAddUsage(builder, usage): builder.PrependUint32Slot(0, usage, 0)
def AttachmentInfoAddFormat(builder, format): builder.PrependUint8Slot(1, format, 0)
def AttachmentInfoAddSamples(builder, samples): builder.PrependUint32Slot(2, samples, 0)
def AttachmentInfoAddClearValueType(builder, clearValueType): builder.PrependUint8Slot(3, clearValueType, 0)
def AttachmentInfoAddClearValue(builder, clearValue): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(clearValue), 0)
def AttachmentInfoEnd(builder): return builder.EndObject()
