# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaScene

class ClearValue(object):
    NONE = 0
    ClearColorFloat = 1
    ClearColorInt = 2
    ClearColorUInt = 3
    ClearDepthStencil = 4

