# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaScene

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClearColorFloat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClearColorFloat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClearColorFloat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClearColorFloat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClearColorFloat
    def Red(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ClearColorFloat
    def Green(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ClearColorFloat
    def Blue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ClearColorFloat
    def Alpha(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ClearColorFloatStart(builder):
    builder.StartObject(4)

def Start(builder):
    ClearColorFloatStart(builder)

def ClearColorFloatAddRed(builder, red):
    builder.PrependFloat32Slot(0, red, 0.0)

def AddRed(builder, red):
    ClearColorFloatAddRed(builder, red)

def ClearColorFloatAddGreen(builder, green):
    builder.PrependFloat32Slot(1, green, 0.0)

def AddGreen(builder, green):
    ClearColorFloatAddGreen(builder, green)

def ClearColorFloatAddBlue(builder, blue):
    builder.PrependFloat32Slot(2, blue, 0.0)

def AddBlue(builder, blue):
    ClearColorFloatAddBlue(builder, blue)

def ClearColorFloatAddAlpha(builder, alpha):
    builder.PrependFloat32Slot(3, alpha, 0.0)

def AddAlpha(builder, alpha):
    ClearColorFloatAddAlpha(builder, alpha)

def ClearColorFloatEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClearColorFloatEnd(builder)
