# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaScene

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClearColorInt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClearColorInt()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClearColorInt(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClearColorInt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClearColorInt
    def Red(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ClearColorInt
    def Green(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ClearColorInt
    def Blue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ClearColorInt
    def Alpha(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ClearColorIntStart(builder): builder.StartObject(4)
def Start(builder):
    return ClearColorIntStart(builder)
def ClearColorIntAddRed(builder, red): builder.PrependInt32Slot(0, red, 0)
def AddRed(builder, red):
    return ClearColorIntAddRed(builder, red)
def ClearColorIntAddGreen(builder, green): builder.PrependInt32Slot(1, green, 0)
def AddGreen(builder, green):
    return ClearColorIntAddGreen(builder, green)
def ClearColorIntAddBlue(builder, blue): builder.PrependInt32Slot(2, blue, 0)
def AddBlue(builder, blue):
    return ClearColorIntAddBlue(builder, blue)
def ClearColorIntAddAlpha(builder, alpha): builder.PrependInt32Slot(3, alpha, 0)
def AddAlpha(builder, alpha):
    return ClearColorIntAddAlpha(builder, alpha)
def ClearColorIntEnd(builder): return builder.EndObject()
def End(builder):
    return ClearColorIntEnd(builder)