# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaScene

import flatbuffers

class DynamicRenderStates(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDynamicRenderStates(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DynamicRenderStates()
        x.Init(buf, n + offset)
        return x

    # DynamicRenderStates
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DynamicRenderStates
    def LineWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DynamicRenderStates
    def DepthBiasConstantFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DynamicRenderStates
    def DepthBiasClamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DynamicRenderStates
    def DepthBiasSlopeFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DynamicRenderStates
    def BlendConstants(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .Color4f import Color4f
            obj = Color4f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DynamicRenderStates
    def DepthBounds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from .Vector2f import Vector2f
            obj = Vector2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DynamicRenderStates
    def FrontStencilCompareMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DynamicRenderStates
    def BackStencilCompareMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DynamicRenderStates
    def FrontStencilWriteMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DynamicRenderStates
    def BackStencilWriteMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DynamicRenderStates
    def FrontStencilReference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DynamicRenderStates
    def BackStencilReference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def DynamicRenderStatesStart(builder): builder.StartObject(12)
def DynamicRenderStatesAddLineWidth(builder, lineWidth): builder.PrependFloat32Slot(0, lineWidth, 0.0)
def DynamicRenderStatesAddDepthBiasConstantFactor(builder, depthBiasConstantFactor): builder.PrependFloat32Slot(1, depthBiasConstantFactor, 0.0)
def DynamicRenderStatesAddDepthBiasClamp(builder, depthBiasClamp): builder.PrependFloat32Slot(2, depthBiasClamp, 0.0)
def DynamicRenderStatesAddDepthBiasSlopeFactor(builder, depthBiasSlopeFactor): builder.PrependFloat32Slot(3, depthBiasSlopeFactor, 0.0)
def DynamicRenderStatesAddBlendConstants(builder, blendConstants): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(blendConstants), 0)
def DynamicRenderStatesAddDepthBounds(builder, depthBounds): builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(depthBounds), 0)
def DynamicRenderStatesAddFrontStencilCompareMask(builder, frontStencilCompareMask): builder.PrependUint32Slot(6, frontStencilCompareMask, 0)
def DynamicRenderStatesAddBackStencilCompareMask(builder, backStencilCompareMask): builder.PrependUint32Slot(7, backStencilCompareMask, 0)
def DynamicRenderStatesAddFrontStencilWriteMask(builder, frontStencilWriteMask): builder.PrependUint32Slot(8, frontStencilWriteMask, 0)
def DynamicRenderStatesAddBackStencilWriteMask(builder, backStencilWriteMask): builder.PrependUint32Slot(9, backStencilWriteMask, 0)
def DynamicRenderStatesAddFrontStencilReference(builder, frontStencilReference): builder.PrependUint32Slot(10, frontStencilReference, 0)
def DynamicRenderStatesAddBackStencilReference(builder, backStencilReference): builder.PrependUint32Slot(11, backStencilReference, 0)
def DynamicRenderStatesEnd(builder): return builder.EndObject()
