# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaScene

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VertexBuffer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VertexBuffer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVertexBuffer(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VertexBuffer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VertexBuffer
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VertexBuffer
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # VertexBuffer
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # VertexBuffer
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from DeepSeaScene.VertexFormat import VertexFormat
            obj = VertexFormat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VertexBufferStart(builder):
    builder.StartObject(4)

def Start(builder):
    VertexBufferStart(builder)

def VertexBufferAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    VertexBufferAddName(builder, name)

def VertexBufferAddOffset(builder, offset):
    builder.PrependUint32Slot(1, offset, 0)

def AddOffset(builder, offset):
    VertexBufferAddOffset(builder, offset)

def VertexBufferAddCount(builder, count):
    builder.PrependUint32Slot(2, count, 0)

def AddCount(builder, count):
    VertexBufferAddCount(builder, count)

def VertexBufferAddFormat(builder, format):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(format), 0)

def AddFormat(builder, format):
    VertexBufferAddFormat(builder, format)

def VertexBufferEnd(builder):
    return builder.EndObject()

def End(builder):
    return VertexBufferEnd(builder)
