if (DEEPSEA_SYSTEM_MSL)
	find_package(MSL COMPONENTS Client REQUIRED)
else()
	if (DEEPSEA_SINGLE_SHARED)
		set(MSL_SHARED OFF CACHE BOOL "")
		set(MSL_INSTALL OFF CACHE BOOL "")
		set(mslDirectory ${CMAKE_CURRENT_SOURCE_DIR}/Render/ModularShaderLanguage)
	else()
		set(MSL_SHARED ${DEEPSEA_SHARED} CACHE BOOL "")
		set(MSL_INSTALL ${DEEPSEA_INSTALL} CACHE BOOL "")
		set(mslDirectory ModularShaderLanguage)
	endif()
	set(MSL_BUILD_TESTS OFF CACHE BOOL "")
	set(MSL_BUILD_DOCS OFF CACHE BOOL "")
	set(MSL_BUILD_COMPILE OFF CACHE BOOL "")
	set(MSL_BUILD_TOOLS OFF CACHE BOOL "")
	set(MSL_OUTPUT_DIR ${DEEPSEA_OUTPUT_DIR} CACHE PATH "")
	set(MSL_EXPORTS_DIR ${DEEPSEA_EXPORTS_DIR} CACHE PATH "")
	set(MSL_ROOT_FOLDER ${DEEPSEA_ROOT_FOLDER}/external/MSL CACHE STRING "")
	add_subdirectory(${mslDirectory})
endif()

ds_glob_library_sources(sources Render src/*.c src/*.h include/*.h include/*.mslh)
ds_add_library(deepsea_render Render ${sources})
ds_target_link_libraries(deepsea_render PRIVATE msl_client)
