# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaSceneLighting

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LightShadowsPrepare(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LightShadowsPrepare()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLightShadowsPrepare(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LightShadowsPrepare
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LightShadowsPrepare
    def LightShadows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LightShadowsPrepare
    def TransformGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(2)
def LightShadowsPrepareStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddLightShadows(builder, lightShadows): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(lightShadows), 0)
def LightShadowsPrepareAddLightShadows(builder, lightShadows):
    """This method is deprecated. Please switch to AddLightShadows."""
    return AddLightShadows(builder, lightShadows)
def AddTransformGroup(builder, transformGroup): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(transformGroup), 0)
def LightShadowsPrepareAddTransformGroup(builder, transformGroup):
    """This method is deprecated. Please switch to AddTransformGroup."""
    return AddTransformGroup(builder, transformGroup)
def End(builder): return builder.EndObject()
def LightShadowsPrepareEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)