# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaSceneLighting

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SceneLightSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SceneLightSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSceneLightSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SceneLightSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SceneLightSet
    def Lights(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from DeepSeaSceneLighting.Light import Light
            obj = Light()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SceneLightSet
    def LightsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SceneLightSet
    def LightsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # SceneLightSet
    def MaxLights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SceneLightSet
    def AmbientColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from DeepSeaScene.Color3f import Color3f
            obj = Color3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SceneLightSet
    def AmbientIntensity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Start(builder): builder.StartObject(4)
def SceneLightSetStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddLights(builder, lights): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(lights), 0)
def SceneLightSetAddLights(builder, lights):
    """This method is deprecated. Please switch to AddLights."""
    return AddLights(builder, lights)
def StartLightsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SceneLightSetStartLightsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartLightsVector(builder, numElems)
def AddMaxLights(builder, maxLights): builder.PrependUint32Slot(1, maxLights, 0)
def SceneLightSetAddMaxLights(builder, maxLights):
    """This method is deprecated. Please switch to AddMaxLights."""
    return AddMaxLights(builder, maxLights)
def AddAmbientColor(builder, ambientColor): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ambientColor), 0)
def SceneLightSetAddAmbientColor(builder, ambientColor):
    """This method is deprecated. Please switch to AddAmbientColor."""
    return AddAmbientColor(builder, ambientColor)
def AddAmbientIntensity(builder, ambientIntensity): builder.PrependFloat32Slot(3, ambientIntensity, 0.0)
def SceneLightSetAddAmbientIntensity(builder, ambientIntensity):
    """This method is deprecated. Please switch to AddAmbientIntensity."""
    return AddAmbientIntensity(builder, ambientIntensity)
def End(builder): return builder.EndObject()
def SceneLightSetEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)