# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaSceneLighting

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShadowCullList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShadowCullList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShadowCullList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShadowCullList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShadowCullList
    def LightShadows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShadowCullList
    def Surface(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(2)
def ShadowCullListStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddLightShadows(builder, lightShadows): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(lightShadows), 0)
def ShadowCullListAddLightShadows(builder, lightShadows):
    """This method is deprecated. Please switch to AddLightShadows."""
    return AddLightShadows(builder, lightShadows)
def AddSurface(builder, surface): builder.PrependUint8Slot(1, surface, 0)
def ShadowCullListAddSurface(builder, surface):
    """This method is deprecated. Please switch to AddSurface."""
    return AddSurface(builder, surface)
def End(builder): return builder.EndObject()
def ShadowCullListEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)