# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaPhysics

class DOF(object):
    TranslateX = 0
    TranslateY = 1
    TranslateZ = 2
    RotlateX = 3
    RotlateY = 4
    RotlateZ = 5
