file(GLOB configFiles ${CMAKE_CURRENT_LIST_DIR}/*.conf)
foreach (configFile ${configFiles})
	get_filename_component(configName ${configFile} NAME)
	string(REPLACE ".conf" "" configName ${configName})
	set_property(GLOBAL PROPERTY ${configName} ${configFile})
endforeach()
