# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaSceneVectorDraw

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VectorImage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VectorImage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVectorImage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VectorImage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VectorImage
    def ImageType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VectorImage
    def Image(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # VectorImage
    def TargetSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from DeepSeaScene.Vector2f import Vector2f
            obj = Vector2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VectorImage
    def SharedMaterials(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VectorImage
    def VectorShaders(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VectorImage
    def Resources(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # VectorImage
    def ResourcesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VectorImage
    def ResourcesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # VectorImage
    def Srgb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VectorImageStart(builder):
    builder.StartObject(7)

def Start(builder):
    VectorImageStart(builder)

def VectorImageAddImageType(builder, imageType):
    builder.PrependUint8Slot(0, imageType, 0)

def AddImageType(builder, imageType):
    VectorImageAddImageType(builder, imageType)

def VectorImageAddImage(builder, image):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(image), 0)

def AddImage(builder, image):
    VectorImageAddImage(builder, image)

def VectorImageAddTargetSize(builder, targetSize):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(targetSize), 0)

def AddTargetSize(builder, targetSize):
    VectorImageAddTargetSize(builder, targetSize)

def VectorImageAddSharedMaterials(builder, sharedMaterials):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(sharedMaterials), 0)

def AddSharedMaterials(builder, sharedMaterials):
    VectorImageAddSharedMaterials(builder, sharedMaterials)

def VectorImageAddVectorShaders(builder, vectorShaders):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(vectorShaders), 0)

def AddVectorShaders(builder, vectorShaders):
    VectorImageAddVectorShaders(builder, vectorShaders)

def VectorImageAddResources(builder, resources):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(resources), 0)

def AddResources(builder, resources):
    VectorImageAddResources(builder, resources)

def VectorImageStartResourcesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartResourcesVector(builder, numElems):
    return VectorImageStartResourcesVector(builder, numElems)

def VectorImageAddSrgb(builder, srgb):
    builder.PrependBoolSlot(6, srgb, 0)

def AddSrgb(builder, srgb):
    VectorImageAddSrgb(builder, srgb)

def VectorImageEnd(builder):
    return builder.EndObject()

def End(builder):
    return VectorImageEnd(builder)
