// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCENEVECTORRESOURCES_DEEPSEASCENEVECTORDRAW_H_
#define FLATBUFFERS_GENERATED_SCENEVECTORRESOURCES_DEEPSEASCENEVECTORDRAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "DeepSea/Scene/Flatbuffers/SceneCommon_generated.h"

namespace DeepSeaSceneVectorDraw {

struct VectorResources;
struct VectorResourcesBuilder;

struct VectorResources FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VectorResourcesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESOURCES_TYPE = 4,
    VT_RESOURCES = 6,
    VT_SHAREDMATERIALS = 8,
    VT_VECTORSHADERS = 10,
    VT_TEXTUREICONSHADER = 12,
    VT_TEXTUREICONMATERIAL = 14,
    VT_SRGB = 16
  };
  DeepSeaScene::FileOrData resources_type() const {
    return static_cast<DeepSeaScene::FileOrData>(GetField<uint8_t>(VT_RESOURCES_TYPE, 0));
  }
  const void *resources() const {
    return GetPointer<const void *>(VT_RESOURCES);
  }
  template<typename T> const T *resources_as() const;
  const DeepSeaScene::FileReference *resources_as_FileReference() const {
    return resources_type() == DeepSeaScene::FileOrData::FileReference ? static_cast<const DeepSeaScene::FileReference *>(resources()) : nullptr;
  }
  const DeepSeaScene::RelativePathReference *resources_as_RelativePathReference() const {
    return resources_type() == DeepSeaScene::FileOrData::RelativePathReference ? static_cast<const DeepSeaScene::RelativePathReference *>(resources()) : nullptr;
  }
  const DeepSeaScene::RawData *resources_as_RawData() const {
    return resources_type() == DeepSeaScene::FileOrData::RawData ? static_cast<const DeepSeaScene::RawData *>(resources()) : nullptr;
  }
  const ::flatbuffers::String *sharedMaterials() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SHAREDMATERIALS);
  }
  const ::flatbuffers::String *vectorShaders() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VECTORSHADERS);
  }
  const ::flatbuffers::String *textureIconShader() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXTUREICONSHADER);
  }
  const ::flatbuffers::String *textureIconMaterial() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXTUREICONMATERIAL);
  }
  bool srgb() const {
    return GetField<uint8_t>(VT_SRGB, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_RESOURCES_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_RESOURCES) &&
           VerifyFileOrData(verifier, resources(), resources_type()) &&
           VerifyOffset(verifier, VT_SHAREDMATERIALS) &&
           verifier.VerifyString(sharedMaterials()) &&
           VerifyOffset(verifier, VT_VECTORSHADERS) &&
           verifier.VerifyString(vectorShaders()) &&
           VerifyOffset(verifier, VT_TEXTUREICONSHADER) &&
           verifier.VerifyString(textureIconShader()) &&
           VerifyOffset(verifier, VT_TEXTUREICONMATERIAL) &&
           verifier.VerifyString(textureIconMaterial()) &&
           VerifyField<uint8_t>(verifier, VT_SRGB, 1) &&
           verifier.EndTable();
  }
};

template<> inline const DeepSeaScene::FileReference *VectorResources::resources_as<DeepSeaScene::FileReference>() const {
  return resources_as_FileReference();
}

template<> inline const DeepSeaScene::RelativePathReference *VectorResources::resources_as<DeepSeaScene::RelativePathReference>() const {
  return resources_as_RelativePathReference();
}

template<> inline const DeepSeaScene::RawData *VectorResources::resources_as<DeepSeaScene::RawData>() const {
  return resources_as_RawData();
}

struct VectorResourcesBuilder {
  typedef VectorResources Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_resources_type(DeepSeaScene::FileOrData resources_type) {
    fbb_.AddElement<uint8_t>(VectorResources::VT_RESOURCES_TYPE, static_cast<uint8_t>(resources_type), 0);
  }
  void add_resources(::flatbuffers::Offset<void> resources) {
    fbb_.AddOffset(VectorResources::VT_RESOURCES, resources);
  }
  void add_sharedMaterials(::flatbuffers::Offset<::flatbuffers::String> sharedMaterials) {
    fbb_.AddOffset(VectorResources::VT_SHAREDMATERIALS, sharedMaterials);
  }
  void add_vectorShaders(::flatbuffers::Offset<::flatbuffers::String> vectorShaders) {
    fbb_.AddOffset(VectorResources::VT_VECTORSHADERS, vectorShaders);
  }
  void add_textureIconShader(::flatbuffers::Offset<::flatbuffers::String> textureIconShader) {
    fbb_.AddOffset(VectorResources::VT_TEXTUREICONSHADER, textureIconShader);
  }
  void add_textureIconMaterial(::flatbuffers::Offset<::flatbuffers::String> textureIconMaterial) {
    fbb_.AddOffset(VectorResources::VT_TEXTUREICONMATERIAL, textureIconMaterial);
  }
  void add_srgb(bool srgb) {
    fbb_.AddElement<uint8_t>(VectorResources::VT_SRGB, static_cast<uint8_t>(srgb), 0);
  }
  explicit VectorResourcesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VectorResources> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VectorResources>(end);
    fbb_.Required(o, VectorResources::VT_RESOURCES);
    return o;
  }
};

inline ::flatbuffers::Offset<VectorResources> CreateVectorResources(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    DeepSeaScene::FileOrData resources_type = DeepSeaScene::FileOrData::NONE,
    ::flatbuffers::Offset<void> resources = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sharedMaterials = 0,
    ::flatbuffers::Offset<::flatbuffers::String> vectorShaders = 0,
    ::flatbuffers::Offset<::flatbuffers::String> textureIconShader = 0,
    ::flatbuffers::Offset<::flatbuffers::String> textureIconMaterial = 0,
    bool srgb = false) {
  VectorResourcesBuilder builder_(_fbb);
  builder_.add_textureIconMaterial(textureIconMaterial);
  builder_.add_textureIconShader(textureIconShader);
  builder_.add_vectorShaders(vectorShaders);
  builder_.add_sharedMaterials(sharedMaterials);
  builder_.add_resources(resources);
  builder_.add_srgb(srgb);
  builder_.add_resources_type(resources_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VectorResources> CreateVectorResourcesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    DeepSeaScene::FileOrData resources_type = DeepSeaScene::FileOrData::NONE,
    ::flatbuffers::Offset<void> resources = 0,
    const char *sharedMaterials = nullptr,
    const char *vectorShaders = nullptr,
    const char *textureIconShader = nullptr,
    const char *textureIconMaterial = nullptr,
    bool srgb = false) {
  auto sharedMaterials__ = sharedMaterials ? _fbb.CreateString(sharedMaterials) : 0;
  auto vectorShaders__ = vectorShaders ? _fbb.CreateString(vectorShaders) : 0;
  auto textureIconShader__ = textureIconShader ? _fbb.CreateString(textureIconShader) : 0;
  auto textureIconMaterial__ = textureIconMaterial ? _fbb.CreateString(textureIconMaterial) : 0;
  return DeepSeaSceneVectorDraw::CreateVectorResources(
      _fbb,
      resources_type,
      resources,
      sharedMaterials__,
      vectorShaders__,
      textureIconShader__,
      textureIconMaterial__,
      srgb);
}

inline const DeepSeaSceneVectorDraw::VectorResources *GetVectorResources(const void *buf) {
  return ::flatbuffers::GetRoot<DeepSeaSceneVectorDraw::VectorResources>(buf);
}

inline const DeepSeaSceneVectorDraw::VectorResources *GetSizePrefixedVectorResources(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<DeepSeaSceneVectorDraw::VectorResources>(buf);
}

template <bool B = false>
inline bool VerifyVectorResourcesBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<DeepSeaSceneVectorDraw::VectorResources>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedVectorResourcesBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<DeepSeaSceneVectorDraw::VectorResources>(nullptr);
}

inline void FinishVectorResourcesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DeepSeaSceneVectorDraw::VectorResources> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVectorResourcesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DeepSeaSceneVectorDraw::VectorResources> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DeepSeaSceneVectorDraw

#endif  // FLATBUFFERS_GENERATED_SCENEVECTORRESOURCES_DEEPSEASCENEVECTORDRAW_H_
