# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaVectorDraw

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClosePathCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsClosePathCommand(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClosePathCommand()
        x.Init(buf, n + offset)
        return x

    # ClosePathCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ClosePathCommandStart(builder): builder.StartObject(0)
def ClosePathCommandEnd(builder): return builder.EndObject()
