# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaVectorDraw

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TextureResource(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TextureResource()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTextureResource(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TextureResource
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TextureResource
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TextureResource
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def TextureResourceStart(builder):
    builder.StartObject(2)

def Start(builder):
    TextureResourceStart(builder)

def TextureResourceAddDataType(builder, dataType):
    builder.PrependUint8Slot(0, dataType, 0)

def AddDataType(builder, dataType):
    TextureResourceAddDataType(builder, dataType)

def TextureResourceAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    TextureResourceAddData(builder, data)

def TextureResourceEnd(builder):
    return builder.EndObject()

def End(builder):
    return TextureResourceEnd(builder)
