# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaVectorDraw

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TextIcons(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TextIcons()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTextIcons(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TextIcons
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TextIcons
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TextIcons
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TextIcons
    def Icons(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from DeepSeaVectorDraw.TextIconGroup import TextIconGroup
            obj = TextIconGroup()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TextIcons
    def IconsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TextIcons
    def IconsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def TextIconsStart(builder):
    builder.StartObject(3)

def Start(builder):
    TextIconsStart(builder)

def TextIconsAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    TextIconsAddName(builder, name)

def TextIconsAddType(builder, type):
    builder.PrependUint8Slot(1, type, 0)

def AddType(builder, type):
    TextIconsAddType(builder, type)

def TextIconsAddIcons(builder, icons):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(icons), 0)

def AddIcons(builder, icons):
    TextIconsAddIcons(builder, icons)

def TextIconsStartIconsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartIconsVector(builder, numElems):
    return TextIconsStartIconsVector(builder, numElems)

def TextIconsEnd(builder):
    return builder.EndObject()

def End(builder):
    return TextIconsEnd(builder)
