# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaVectorDraw

class VectorResourceUnion(object):
    NONE = 0
    TextureResource = 1
    VectorImageResource = 2
    TextIcons = 3
    FaceGroup = 4
    Font = 5
