# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaVectorDraw

import flatbuffers

class VectorResources(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVectorResources(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VectorResources()
        x.Init(buf, n + offset)
        return x

    # VectorResources
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VectorResources
    def Textures(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Resource import Resource
            obj = Resource()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VectorResources
    def TexturesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VectorResources
    def FaceGroups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FaceGroup import FaceGroup
            obj = FaceGroup()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VectorResources
    def FaceGroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VectorResources
    def Fonts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Font import Font
            obj = Font()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VectorResources
    def FontsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def VectorResourcesStart(builder): builder.StartObject(3)
def VectorResourcesAddTextures(builder, textures): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(textures), 0)
def VectorResourcesStartTexturesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def VectorResourcesAddFaceGroups(builder, faceGroups): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(faceGroups), 0)
def VectorResourcesStartFaceGroupsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def VectorResourcesAddFonts(builder, fonts): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fonts), 0)
def VectorResourcesStartFontsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def VectorResourcesEnd(builder): return builder.EndObject()
