# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DeepSeaVectorDraw

class VectorCommandUnion(object):
    NONE = 0
    StartPathCommand = 1
    MoveCommand = 2
    LineCommand = 3
    BezierCommand = 4
    QuadraticCommand = 5
    ArcCommand = 6
    ClosePathCommand = 7
    EllipseCommand = 8
    RectangleCommand = 9
    StrokePathCommand = 10
    FillPathCommand = 11
    TextCommand = 12
    TextRangeCommand = 13
    ImageCommand = 14
