set(extraLibs)
set(extraIncludeDirs)
set(extraDefines)
if (APPLE)
	set(extraLibs "-framework AppKit" "-framework OpenGL")
elseif (DEEPSEA_GLES)
	find_package(EGL REQUIRED)
	set(extraLibs ${EGL_LIBRARIES})
	set(extraIncludeDirs ${EGL_INCLUDE_DIRS})
	set(extraDefines PRIVATE ANYGL_GLES=1)
elseif (UNIX)
	find_package(X11 REQUIRED)
	find_package(GLX REQUIRED)
	set(extraLibs ${X11_LIBRARIES} ${GLX_LIBRARIES})
	set(extraIncludeDirs ${X11_INCLUDE_DIRECTORIES} ${GLX_INCLUDE_DIRECTORIES})
endif()

set(extraPatterns)
if (APPLE)
	set(extraPatterns src/*.m)
endif()
ds_glob_library_sources(sources Render/RenderOpenGL src/*.c src/*.h include/*.h ${extraPatterns})
ds_add_library(deepsea_render_opengl Render/RenderOpenGL ${sources})
ds_target_include_directories(deepsea_render_opengl
	PRIVATE ${OPENGL_INCLUDE_DIR} ${extraIncludeDirs} ${DEEPSEA_SOURCE_DIR}/Render/RenderOpenGL/src)
ds_target_link_libraries(deepsea_render_opengl
	PRIVATE ${CMAKE_DL_LIBS} ${OPENGL_gl_LIBRARY} ${extraLibs} msl_client)
if (extraDefines)
	ds_target_compile_definitions(deepsea_render_opengl ${extraDefines})
endif()
